- name: Deploy aistor
  hosts: control_plane[0]
  become: false
  gather_facts: true

  tasks:
    - name: Deploy aistor release
      shell: |
        kubectl --kubeconfig="{{ ansible_user_dir }}/.kube/config" apply -k https://min.io/k8s/aistor

    - name: Create aistor ingress
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ ansible_user_dir }}/.kube/config"
        template: aistor-ingress.yaml.j2