- name: Deploy aistor ingress
  hosts: control_plane[0]
  become: true
  gather_facts: false

  tasks:
    - name: Create aistor ingress
      kubernetes.core.k8s:
        state: present
        kubeconfig: /home/{{ ansible_user }}/.kube/config
        template: aistor-ingress.yaml.j2
