- name: Deploy aistor
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Deploy aistor CRDs
      shell: |
        kubectl --kubeconfig={{ kubeconfig }} apply -f http://ns-3.k1.min.dev/dev/crds.yaml

    - name: Deploy aistor resources
      shell: |
        kubectl --kubeconfig={{ kubeconfig }} apply -f http://ns-3.k1.min.dev/dev/aistor.yaml

    - name: Create aistor ingress
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ kubeconfig }}"
        template: aistor-ingress.yaml.j2
