- name: Deploy aistor
  hosts: control_plane[0]
  become: false
  gather_facts: true

  tasks:
    - name: Deploy aistor CRDs
      shell: |
        kubectl --kubeconfig="{{ ansible_user_dir }}/.kube/config" apply -f http://ns-3.k1.min.dev/dev/crds.yaml

    - name: Deploy aistor resources
      shell: |
        kubectl --kubeconfig="{{ ansible_user_dir }}/.kube/config" apply -f http://ns-3.k1.min.dev/dev/aistor.yaml

    - name: Create aistor ingress
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ ansible_user_dir }}/.kube/config"
        template: aistor-ingress.yaml.j2
