- name: Deploy directpv
  hosts: localhost
  gather_facts: false
  vars:
    drives_file: "{{ playbook_dir }}/drives.yaml"

  tasks:
    - name: Install directpv
      ansible.builtin.command:
        cmd: kubectl directpv install --kubeconfig={{ kubeconfig }} --node-selector directpv=yes

    - name: Discover directpv drives
      ansible.builtin.command:
        cmd: kubectl directpv discover --kubeconfig={{ kubeconfig }} --output-file={{ drives_file }}

    - name: Initialize directpv drives
      ansible.builtin.command:
        cmd: kubectl directpv init --kubeconfig={{ kubeconfig }} --dangerous {{ drives_file }}
