---
- name: Install K3s Control Plane
  hosts: control_plane
  become: true
  tasks:
    - name: Download K3s install script
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s_install.sh
        mode: "0700"

    - name: Install K3s server
      ansible.builtin.shell: /tmp/k3s_install.sh
      environment:
        INSTALL_K3S_EXEC: "server --disable traefik"

    - name: Get node token
      ansible.builtin.shell: cat /var/lib/rancher/k3s/server/node-token
      register: node_token

- name: Install K3s Agents
  hosts: nodes
  become: true
  tasks:
    - name: Download K3s install script
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s_install.sh
        mode: "0700"

    - name: Install K3s agent
      ansible.builtin.shell: /tmp/k3s_install.sh
      environment:
        K3S_URL: "https://{{ hostvars[groups['control_plane'][0]]['ansible_host'] }}:6443"
        K3S_TOKEN: "{{ hostvars[groups['control_plane'][0]]['node_token']['stdout'] }}"

- name: Configure kubectl on control plane
  hosts: control_plane[0]
  become: false
  tasks:
    - name: Create .kube directory
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.kube"
        state: directory
        mode: "0755"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Copy kubeconfig to user home
      ansible.builtin.copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ ansible_user_dir }}/.kube/config"
        remote_src: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"
      become: true

    - name: Update kubeconfig server address
      ansible.builtin.replace:
        path: "{{ ansible_user_dir }}/.kube/config"
        regexp: "https://127.0.0.1:6443"
        replace: "https://{{ ansible_host }}:6443"

    - name: Ensure kubeconfig directory exists
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.storctl/kubeconfigs"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true
      become: false

    - name: Fetch kubeconfig to Ansible control host
      ansible.builtin.fetch:
        src: "{{ ansible_user_dir }}/.kube/config"
        dest: "{{ kubeconfig }}"
        flat: yes
      become: false

- name: Apply labels and taints to Kubernetes nodes
  hosts: control_plane[0]
  become: false
  tasks:
    - name: Check if kubeconfig file exists
      stat:
        path: "{{ ansible_user_dir }}/.kube/config"
      register: kubeconfig_file

    - name: Fail if kubeconfig file does not exist
      fail:
        msg: "Kubeconfig file not found at {{ ansible_user_dir }}/.kube/config"
      when: not kubeconfig_file.stat.exists

    - name: Apply labels to Kubernetes nodes
      kubernetes.core.k8s:
        kind: Node
        name: "{{ item }}"
        kubeconfig: "{{ ansible_user_dir }}/.kube/config"
        definition:
          metadata:
            labels:
              directpv: "yes"
      loop: "{{ groups['nodes'] }}"

    - name: Apply taint to Kubernetes control plane node
      kubernetes.core.k8s_taint:
        kubeconfig: "{{ ansible_user_dir }}/.kube/config"
        state: present
        name: "{{ hostvars[groups['control_plane'][0]]['inventory_hostname'] }}"
        taints:
          - key: "node-role.kubernetes.io/control-plane"
            effect: "NoSchedule"
