---
- import_playbook: prerequisites.yml
- import_playbook: k3s.yml
- import_playbook: cert-manager.yml
- import_playbook: ingress-nginx.yml
- import_playbook: directpv.yml
- import_playbook: aistor-edge.yml
