providers:
- name: "hetzner"
  token: "your-provider-token-here"
  location: "hel1"
- name: "lima"
  token: "your-provider-token-here"
  location: "us-east-1"
dns:
  provider: "cloudflare"
  domain: "your-domain-here"
  token: "your-dns-token-here"
  zone_id: "your-zone-id-here"

storage:
  type: postgres # or "local" for boltdb
  postgres:
    host: localhost
    port: 5432
    database: storctl_dev
    user: postgres
    password: storctl
  local:
    path: /tmp/storctl.db
    bucket: labs

email: "your-email@example.com"
organization: "your-organization-name"
owner: "your-name"
outputformat: ""
loglevel: ""
