apiVersion: v1
kind: Lab
metadata:
  name: aistor-lab1
  labels:
    project: aistor
spec:
  ttl: 24h
  provider: hetzner
  location: nbg1
  servers:
  - name: cp # control plane server; make sure it ends with 'cp'
    serverType: cx22
    image: ubuntu-24.04
  - name: node-01 # worker node
    serverType: cx22
    image: ubuntu-24.04
  - name: node-02 # worker node
    serverType: cx22
    image: ubuntu-24.04
  volumes:
  - name: volume-01
    server: node-01
    size: 100
    automount: false
    format: xfs
  - name: volume-02
    server: node-01
    size: 100
    automount: false
    format: xfs
  - name: volume-03
    server: node-01
    size: 100
    automount: false
    format: xfs
  - name: volume-04
    server: node-01
    size: 100
    automount: false
    format: xfs
  - name: volume-05
    server: node-02
    size: 100
    automount: false
    format: xfs
  - name: volume-06
    server: node-02
    size: 100
    automount: false
    format: xfs
  - name: volume-07
    server: node-02
    size: 100
    automount: false
    format: xfs
  - name: volume-08
    server: node-02
    size: 100
    automount: false
    format: xfs
