apiVersion: v1
kind: Lab
metadata:
  name: my-lab
  labels:
    project: security-training
spec:
  servers:
  - name: master
    provider: hetzner
    location: nbg1
    serverType: cx31
    ttl: 48h
    image: ubuntu-24.04
  volumes:
  - name: data
    size: 100GB
    location: nbg1
    ttl: 48h
  keys:
  - name: ssh-key
    type: ssh
    ttl: 48h
