providers:
- name: "hetzner"
  token: "your-provider-token-here"
  location: "hel1"
- name: "lima"
  location: "local"
- name: "virt"
  location: "local"
dns:
  provider: "cloudflare"
  domain: "your-domain-here"
  token: "your-dns-token-here"
  zone_id: "your-zone-id-here"

email: "your-email@example.com"
organization: "your-organization-name"
owner: "your-name"
outputformat: ""
loglevel: ""
