email: "pavel.anni@gmail.com"
kubernetes_context: "default"
kubeconfig: "{{ playbook_dir }}/{{ lab_name }}-kubeconfig"
base_packages:
- curl
- apt-transport-https
- ca-certificates
- software-properties-common
- python3
- python3-pip
- iptables
- ntp
