email: "pavel.anni@gmail.com"
kubernetes_context: "default"
kubeconfig: "{{ lookup('env', 'HOME') }}/.storctl/kubeconfigs/{{ lab_name }}-kubeconfig"
base_packages:
- curl
- apt-transport-https
- ca-certificates
- software-properties-common
- python3
- python3-pip
- python3-kubernetes
- iptables
- ntp
